export const ERROR_CODES = {
  // Validation Errors
  VALIDATION_FAILED: "VALIDATION_FAILED",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  CIRCULAR_REFERENCE: "CIRCULAR_REFERENCE",
  NESTING_TOO_DEEP: "NESTING_TOO_DEEP",

  // Database Errors
  DATABASE_ERROR: "DATABASE_ERROR",
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",

  // File Upload Errors
  FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_PROCESSING_ERROR: "FILE_PROCESSING_ERROR",

  // OAuth2 Errors
  OAUTH2_INVALID_REQUEST: "OAUTH2_INVALID_REQUEST",
  OAUTH2_INVALID_CLIENT: "OAUTH2_INVALID_CLIENT",
  OAUTH2_INVALID_GRANT: "OAUTH2_INVALID_GRANT",
  OAUTH2_INVALID_SCOPE: "OAUTH2_INVALID_SCOPE",
  OAUTH2_INVALID_TOKEN: "OAUTH2_INVALID_TOKEN",
  OAUTH2_INSUFFICIENT_SCOPE: "OAUTH2_INSUFFICIENT_SCOPE",
  OAUTH2_ACCESS_DENIED: "OAUTH2_ACCESS_DENIED",
  OAUTH2_UNSUPPORTED_RESPONSE_TYPE: "OAUTH2_UNSUPPORTED_RESPONSE_TYPE",
  OAUTH2_UNSUPPORTED_GRANT_TYPE: "OAUTH2_UNSUPPORTED_GRANT_TYPE",
  OAUTH2_UNAUTHORIZED_CLIENT: "OAUTH2_UNAUTHORIZED_CLIENT",
  OAUTH2_SERVER_ERROR: "OAUTH2_SERVER_ERROR",

  // Authentication/Authorization Errors
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  // Rate Limiting
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

  // General Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
